<?php $this->load->view('frontend/inc/header') ?>

<div id="banner-area" class="banner-area" style="background:url(assets/frontend/images/banner/banner9.jpeg) rgba(20, 20, 20, 0.5);">
    <div class="banner-text">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="banner-heading">
                        <h1 class="banner-title">Terms</h1>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb justify-content-center">
                                <li class="breadcrumb-item"><a href="<?= base_url() ?>">Home</a></li>
                                <li class="breadcrumb-item"><a href="#">company</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Terms</li>
                            </ol>
                        </nav>
                    </div>
                </div><!-- Col end -->
            </div><!-- Row end -->
        </div><!-- Container end -->
    </div><!-- Banner text end -->
</div><!-- Banner area end -->

<section id="main-container" class="main-container">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h3 class="column-title">Terms & Conditions</h3>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><strong><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>TERMS &amp; CONDITION</span></strong></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>The laws and restrictions for using the DIGITALNOWONLINE Website are outlined in these terms and conditions. DIGITALNOWONLINE can be found at: We assume that by accessing this website, you agree to these terms and conditions in its entirety. If you do not agree to all of the terms and conditions listed on this page, do not use the DIGITALNOWONLINE website. The terms &quot;Client,&quot; &quot;You,&quot; and &quot;Your&quot; refer to you, the person accessing this website and accepting the Company&apos;s terms and conditions. &quot;Terms and Conditions,&quot; &quot;Privacy Statement,&quot; and &quot;Disclaimer Notice&quot; refer to these Terms and Conditions, Privacy Statement, and Disclaimer Notice, and any or all Agreements: &quot;Client,&quot; &quot;You,&quot; and &quot;Your&quot; refer to you, the person accessing this website and accepting the Company&apos;s terms and conditions.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>Our Company is referred to as &quot;The Company,&quot; &quot;Ourselves,&quot; &quot;We,&quot; &quot;Ours,&quot; and &quot;Us.&quot; Both the Client and ourselves, or either the Client or ourselves, are referred to as &quot;Party,&quot; &quot;Parties,&quot; or &quot;Us.&quot; All terms refer to the offer, acceptance, and consideration of payment necessary to begin the process of our assistance to the Client in the most appropriate manner, whether by formal meetings of a fixed duration, or any other means, for the express purpose of meeting the Client&apos;s needs in respect of provision of the Company&apos;s stated services/products, in accordance with and subject to prevailing law. Any use of the above language, as well as other words in the singular, plural, capitalization, and/or he/she or they, is assumed to mean the same thing.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><strong><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>Cookies</span></strong></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>Cookies are used on this site. By using the DIGITALNOWONLINE website, you agree to the DIGITALNOWONLINE privacy policy&apos;s use of cookies. Cookies are used by the majority of current interactive web sites to allow us to retrieve user information for each visit. Cookies are used in several areas of our site to ensure that they perform properly and are easy to use for visitors. Cookies may also be used by certain of our affiliate / advertising partners.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><strong><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>License</span></strong></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>Unless otherwise specified, all material on DIGITALNOWONLINE is the intellectual property of Digitalnowonline.online and/or its licensors. All rights to intellectual property are reserved. Subject to the restrictions set forth in these terms and conditions, you may access and/or print pages from DIGITALNOWONLINE for your own personal use.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><strong><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>User Remarks</span></strong></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>Users can publish and exchange ideas, information, material, and data (&apos;Comments&apos;) in some areas of our website. DIGITALNOWONLINE does not check, edit, publish, or review Comments before they appear on the website, and Comments do not reflect the views or opinions of DIGITALNOWONLINE, its agents, or affiliates in any way. The person who writes the comment expresses his or her point of view and viewpoint. DIGITALNOWONLINE shall not be responsible or liable for the Comments or for any loss, cost, responsibility, damages or expenses caused and or suffered as a result of the use of and/or posting of and/or appearance of the Comments on this website, to the extent permitted by relevant laws.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>DIGITALNOWONLINE has the right to monitor all Comments and to remove any Comments that it deems improper, offensive, or in violation of these Terms and Conditions.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><strong><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>You warrant and represent that</span></strong></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>&nbsp;You have all necessary permissions and consents to post the Comments on our website. The Comments do not infringe on any third-party intellectual property rights, such as copyright, patents, or trademarks.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>There is nothing in the Comments that is defamatory, libelous, offensive, indecent, or otherwise prohibited, or that is an invasion of privacy. The Comments will not be used to solicit or promote business, custom, or current commercial or illegal conduct. You hereby grant DIGITALNOWONLINE a non-exclusive royalty-free right to use, reproduce, edit, and authorize others to use, reproduce, edit, and authorize others to use, reproduce, and edit any of your Comments in any form, format, or media.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><strong><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>Creating a Link to Our Content</span></strong></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>Without prior written permission, the following organizations may link to our website: When they list us in the directory, online directory distributors may link to our website in the same way that they link to the websites of other listed businesses; and Systemwide Accredited Businesses, with the exception of soliciting non-profit organizations, charity shopping malls, and charity fundraising groups, which are not permitted to link to our website.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>These organizations may link to our home page, publications, or other Web site content as long as the link:&nbsp;</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>(a) Is not deceptive;&nbsp;</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>(b) Does not falsely imply sponsorship, support, or approval of the linking party or its products or services; and</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>&nbsp;(c) Is appropriate for the linking party&apos;s site.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>Other link requests from the following types of organizations may be considered and approved at our sole discretion: well-known consumer and/or business information sources such as Chambers of Commerce, American Automobile Association, AARP, and Consumers Union; dot.com community sites associations or other groups representing charities, including charity giving sites; accounting, law, and consulting firms whose primary clients are businesses; online directory distributors.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>We will approve link requests from these organizations if we determine that:</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>&nbsp;(a) The link would not reflect unfavorably on us or our accredited businesses (for example, trade associations or other organizations representing inherently suspect types of business, such as work-at-home opportunities)</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>(b) The organization does not have an unsatisfactory record with us</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>(c) Where the benefit of the hyperlink&apos;s exposure overcomes the lack of DIGITALNOWONLINE</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>(d) Where the link is in the context of general resource information or is otherwise compatible with editorial content in a newsletter or similar product advancing the organization&apos;s goal.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>These organizations may link to our home page, publications, or other Web site content as long as the link:&nbsp;</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>(a) Is not deceptive</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>&nbsp;(b) Does not falsely imply sponsorship, support, or approval of the linking party or its products or services</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>(c) Is appropriate for the linking party&apos;s site.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>If you are a member of one of the organizations named in paragraph 2 above and would like to link to our website, please contact us at www.@Digitalnowonline.com. Include your name, the name of your organization, contact information (such as a phone number and/or e-mail address), the URL of your site, a list of any URLs from which you intend to link to our Web site, and a list of the URL(s) on our site to which you would like to link. Allow for a response time of two to three weeks.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><strong><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>Approved organizations may link to our Web site by using our corporate name</span></strong><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>&nbsp;The unified resource locator (URL) being linked to, or any other description of our Web site or material being linked to that makes sense in the context and format of content on the linking party&apos;s site. Without a trademark license agreement, no use of (cnamelogo)&apos;s or other artwork for linking will be permitted.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><strong><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>Iframes</span></strong></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>You may not construct frames around our Web pages or use other techniques that affect the visual presentation or look of our Web site without prior approval and express written consent.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><strong><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>Liability for Content</span></strong></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>We will not be held liable or responsible for any content found on your website. You agree to defend and indemnify us against any and all claims arising from or related to your Website. No link(s) may appear on any page of your website or in any context containing content or materials that could be construed as defamatory, obscene, or criminal, or that infringes, otherwise violates, or encourages the infringement or other violation of any third-party rights.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><strong><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>Rights Reservations</span></strong></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>We reserve the right to request, at any time and at our sole discretion, that you delete all links to our Web site, or any specific link to our Web site. Upon such a request, you agree to remove all connections to our website immediately. We have the right to change these terms and conditions, as well as the linking policy, at any moment. You agree to be governed by and abide by these linking terms and conditions if you continue to link to our website.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><strong><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>Our website&apos;s removal links</span></strong></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>You may contact us if you find any link on our Web site or any connected web site offensive for any reason. Requests to remove links will be considered, but we will not be obligated to do so or to react directly to you.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>While we make every effort to ensure that the information on this website is correct, we cannot guarantee its completeness or accuracy, nor can we guarantee that the website will continue available or that the information on the website will be kept up to date.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><strong><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>Disclaimer</span></strong></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>To the fullest extent permissible by law, we disclaim any representations, warranties, and conditions relating to our website and its use (including, without limitation, any implied warranties of satisfactory quality, fitness for purpose, and/or the use of reasonable care and skill). Nothing in this disclaimer is intended to:</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>Limit or exclude our or your liability for negligence-related death or personal harm, as well as our or your liability for fraud or fraudulent misrepresentation. Any limitation or exclusion of our or your liabilities that is not permitted by applicable law, or any limitation or exclusion of our or your liabilities that is not permitted by applicable law. The following are the liability restrictions and exclusions set forth in this section and elsewhere in this disclaimer:&nbsp;</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>(a) Is governed by the preceding sentence; and&nbsp;</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>(b) Govern all obligations arising out of or in connection with the disclaimer or the subject matter of the disclaimer, including liabilities arising out of contract, tort (including negligence), and breach of statutory duty.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>We will not be liable for any loss or damage of any kind to the extent that the website and the information and services on the website are given free of charge.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><strong><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>POLICY ON COOKIES</span></strong></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><strong><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>Information about cookies</span></strong></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>When you visit most websites, cookies are very little files that are kept on your computer. They are transmitted back and forth between the website&apos;s server and your browser in order for the website to remember your actions.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><strong><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>Cookies and how we utilize them</span></strong></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>By analyzing web traffic and tracking user behavior, we utilize cookies to assist enhance the functioning of this website. A security cookie is also used to identify the developers of our website. Cookies cannot transport viruses or install malware on your computer, and the majority of them just contain randomly generated numbers.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><strong><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>Google Tag, CNO Token, XSRF-TOKEN</span></strong></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>The token for validated authentication is saved in cookies for this purpose. This is a cookie called HttpOnly.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><strong><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>Cookie management</span></strong></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>Most Internet browsers have settings that allow users to decide whether or not cookies are accepted. To learn how to configure these settings on a variety of popular browsers, go to Wiki HTTP Cookie.</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><strong><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>Modifications to this privacy notice</span></strong></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'><span style='font-size:19px;line-height:107%;font-family:"Times New Roman","serif";'>Our privacy notice is reviewed on a regular basis.</span></p>

            </div><!-- Col end -->
        </div><!-- Content row end -->

    </div><!-- Container end -->
</section><!-- Main container end -->

<?php $this->load->view('frontend/inc/footer') ?>